language: node_js
before_deploy:
- git config --global user.email publish@travis.github
- git config --global user.name "Travis"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/gnome-id/gnome-id.github.io.git
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  before_script:
  - npm install
  script: 
  - hexo generate
  - gulp deploy
  on:
    branch: development
