language: node_js
before_deploy:
- git config --global user.email publish@travis.github
- git config --global user.name "Travis"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/gnome-id/gnome-id.github.io.git
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  before_script:
  - npm install
  - hexo generate
  script: gulp deploy
  on:
    branch: development
env:
  global:
  - secure: W2thJ02lLtdYQSDUee3lxMh0KtZgjnFBJKfr/cqdvmKAGZzhNVWM5SquorA5Z/8vlozjwQ7uPmsE2mMVHWNLW+xZ8+6OIQnQquPKUEdBWwmUdnUApQIQQYTBypNhy4XvpcgrmWPS41bOFJxDviqOJyC8cbw7Qa7QPaw9ZRqfN3pbyrWgYR1UulynM8RyM6m+GvWyP5XeikBvLIF8VP+vgFOUXhvS7O2nhpnOyaenrcN78J/YbiLnKh33kBnAKrNVoRyikDfNsTFkU1eDmROEwpaaD7PuaY+3nG5xc0gfj55FdZmFlVLWfZQhCuOG92QqHLaQfW0yE7hTLS+lNK2qwh2CyqjgGwbXan/iSq/+FO0Ug9B1+6N+KqkPKen5jGkuBwa/RRtP8u6vTnayAuy0Y0qZFoVys1S3JELy9q+lazAo6M1mCtsbx0Qapiy5leol57wNKB3fofnxUSshgQKZiYIENL2pwPBfqNzeOQc/DBz4MrjTkIZILNHL1QH6a2XMUQ2FvlusgcZDhaNSv1RKVnuXuBkYQnNaFeHTVG/LS7Bscq5V2wZA1+b1/1h9sQQb5s96rQD+o0E3rxOFTdrYwaUTj01pYZVN5r/nQHQ7DhP4zD/iC83CMBN5c480aI3BYUpwabhSbs4AXp0TCPANga7dgSJR7Qg1uJrL02NfsCI=
