language: node_js
branches:
  only:
  - development
before_deploy:
- git config --global user.email publish@travis.github
- git config --global user.name "Travis"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/gnome-id/gnome-id.github.io.git
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  before_script:
  - npm install
  - npm install hexo-cli -g
  script: hexo g -d
  on:
    branch: development
env:
  global:
    secure: LbKda/yO389vL8+MexlpVfge1Aa/TXT1fR0wVVe6L9amGFaxkrwSbbdyQTnm9WxYHBiChE0OTm9f7b8pgLBNc93gP3dAnwXj7OJhkV4q9HqMh/yabSbZ6KFDke0YXdr6YW/Ss4Elu0VpP1NS2GOjUbr2yLt+5Q+Zucx+m1VkGe603aSMNqfY6dj/G9m7N6kMUD5B1EZOuIl+QoaVp+9az30rbxvNiMVa0oBOw2WP8el7KA2cPc3pbuNagf92DsgrcMC66Gtcnu62iKiISd+ZM9X3WsIS2Ex6UyFGHt+lpKmKDJiaERz4A/K7zI9Ex20fq1EzNmX4qKVOo9KX63SmIW0RCs0tXBD25hp7RrcU9VqNVtaZPa7iAh5/NVcl7vW5/ZHftFW3sqG+FdUbW7/emtY7c3VKq9WuDl8jrb4wwfti/WPSdrVuUimZZAvbEexgxlU8Qfha8yEbsRDviJDKdVZV3bgHJcobSqS8NVs4/sjC/dpXoORDS7BzzSmYohtD8k78WeTBK6fHE8cIB6eB7W6pldL9JUAM7PcZtvOvQnt86uM7oVgNmMZkxAmQn0nDhfc4zcUEFpRZC67YQfPIiBTlKlx7hf8i912Eh2MIFrY96KqvdXTNcu5ubfVMoitwi77jsRpiqsEMruxF7Y1O9hst8r4DHKIF6G0/UDxb8N4=
