language: node_js
before_deploy:
- git config --global user.email publish@travis.github
- git config --global user.name "Travis"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/gnome-id/gnome-id.github.io.git
deploy:
- edge: true
  skip_cleanup: true
  provider: script
  before_script:
  - npm install
  - hexo generate
  script: gulp deploy
  on:
    branch: development
env:
  global:
    secure: aJLtmTfmeo1ly7bmf/s1LCJAeiVmU9hShIjL2aBQdYEtVGJ3EWtEIyObrF5t19booDCLjz7mMlIolFt8Km5zDVQvsop4qnxQvjtQ6BEViMN2HFlsF3OVhNg+O9kP1m9fKTWkzBRlIecDQLLbcOzmJnvAjpzdhkbVdwajh3KQogx+Rq6ME5tZtWjq5svwNs6yZ0GtuUNDd97ZgLPxTS+VDDqC7FL4iTNZS/Uwq67QZWWD/NhaVxzQvv3EuBDz1m5Omg+lJUSE6S8JvnmqZp69J1k+Fr3gzqRpAzk4bVafB/Xh3ue1tcs71ZlBN5NPDnuO+ig3/L8nIGlwT1TZLnVw0cPSXlF2g0Il/U8zPvhRb4P7+9U5yV6HHs63t896j3HAnJ/v72GpwoZEJIlBzANWr2WMIEj+RTSTxS36Ekez9cBBZYM9+EH8J28lqCITnPG5fwKaRCNLtTjJeNDeK13ByIIRAv7CjldUOzHYKEj1WyyT4DA8hbR82H+J5NY/cQfS2Ax1A011U0GXo6/qlTSzVT//K4WEz//blNAup3mHSm7zhGXu1SxNlfFwUffqPYuW28gTgeixEPqaxq6LCgtap8GbrOCnrA4K+Xzz5TmeDltMaIaxlP5O9GM3lsYeU8Se/1ETUdp/UvZGFiePOAEyrPyLxlw5CQlyJplcxi/Vxcs=
